---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - agentic.networking.x-k8s.io
  resources:
  - xaccesspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentic.networking.x-k8s.io
  resources:
  - xaccesspolicies/finalizers
  verbs:
  - update
- apiGroups:
  - agentic.networking.x-k8s.io
  resources:
  - xaccesspolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - authpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
