apiVersion: agentic.networking.x-k8s.io/v1alpha1
kind: AccessPolicy
metadata:
  labels:
    app.kubernetes.io/name: accesspolicy
    app.kubernetes.io/managed-by: kustomize
  name: accesspolicy-sample
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: mcp-gateway
  action: Allow
  rules:
    - name: allow-search-web-only
      source:
        type: ServiceAccount
        serviceAccount:
          name: default
      authorization:
        type: CEL
        cel:
          expression: "request.mcp.tool_name == 'search_web'"
